# Generated by Django 5.2.16 on 2026-09-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FortuneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล')),
                ('gender', models.CharField(default='male', max_length=10, verbose_name='เพศ')),
                ('birth_day', models.IntegerField(default=1, verbose_name='วันเกิด')),
                ('birth_month', models.IntegerField(default=1, verbose_name='เดือนเกิด')),
                ('birth_year', models.IntegerField(default=1995, verbose_name='ปีเกิด')),
                ('birth_hour', models.IntegerField(default=9, verbose_name='ชั่วโมงเกิด')),
                ('birth_minute', models.IntegerField(default=30, verbose_name='นาทีเกิด')),
                ('province', models.CharField(default='กรุงเทพมหานคร', max_length=100, verbose_name='จังหวัด')),
                ('country', models.CharField(default='ประเทศไทย', max_length=100, verbose_name='ประเทศ')),
                ('chart_data', models.JSONField(blank=True, null=True, verbose_name='ข้อมูลดวงที่วิเคราะห์')),
                ('status', models.CharField(default='Active', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('last_analyzed_at', models.DateTimeField(auto_now=True, verbose_name='วิเคราะห์ล่าสุดเมื่อ')),
            ],
            options={
                'ordering': ['-last_analyzed_at'],
            },
        ),
    ]
